From 6afdba757b8b1bfa71d741c86f2eb5149358a858 Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Wed, 16 Feb 2022 18:28:06 +0100
Subject: [PATCH 16/54] timeout_call returns the result of user function now

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/util.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/drivers/util.py b/drivers/util.py
index 7eb89b1..5a7b4e5 100755
--- a/drivers/util.py
+++ b/drivers/util.py
@@ -849,7 +849,7 @@ def timeout_call(timeoutseconds, function, *arguments):
     signal.signal(signal.SIGALRM, handler)
     signal.alarm(timeoutseconds)
     try:
-        function(*arguments)
+        return function(*arguments)
     finally:
         signal.alarm(0)
 
-- 
2.36.0

