From 1e33439ce7625c6a15135c033496b06592b99df7 Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Fri, 8 Jul 2022 14:52:25 +0200
Subject: [PATCH 064/170] fix(cleanup): print LINSTOR VDI UUID if error during
 info loading (not SR UUID)

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/cleanup.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/drivers/cleanup.py b/drivers/cleanup.py
index 0399389..77b38c2 100755
--- a/drivers/cleanup.py
+++ b/drivers/cleanup.py
@@ -2969,7 +2969,7 @@ class LinstorSR(SR):
             except Exception as e:
                 Util.log(
                     ' [VDI {}: failed to load VDI info]: {}'
-                    .format(self.uuid, e)
+                    .format(vdi_uuid, e)
                 )
                 info = vhdutil.VHDInfo(vdi_uuid)
                 info.error = 1
-- 
2.44.0

