From 8f0db6d15c8e68f4ebe6aeedb1f9cc99f2957a63 Mon Sep 17 00:00:00 2001
From: Ronan Abhamon <ronan.abhamon@vates.fr>
Date: Thu, 18 Jan 2024 10:24:01 +0100
Subject: [PATCH 155/177] fix(LinstorSR): explicit error message when a group
 is not unique during SR creation

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.fr>
---
 drivers/LinstorSR.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/drivers/LinstorSR.py b/drivers/LinstorSR.py
index a73ae5a2..fed1de2b 100755
--- a/drivers/LinstorSR.py
+++ b/drivers/LinstorSR.py
@@ -569,7 +569,9 @@ class LinstorSR(SR.SR):
                 if group_name and group_name == self._group_name:
                     raise xs_errors.XenError(
                         'LinstorSRCreate',
-                        opterr='group name must be unique'
+                        opterr='group name must be unique, already used by PBD {}'.format(
+                            xenapi.PBD.get_uuid(pbd)
+                        )
                     )
 
         if srs:
